name: Deploy FastFoodSoatLambdaCredential Middleware

on:
  push:
    branches: [ "main" ]
    paths:
      - "middleware-service/**"
      - "common/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew :middleware-service:clean :middleware-service:build shadowJar

      - name: Package Lambda
        run: zip -j middleware-service.zip middleware-service/build/libs/*-all.jar

      - name: Upload to S3
        run: aws s3 cp middleware-service.zip s3://my-bucket/middleware-service.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        working-directory: ./middleware-service/terraform
        run: terraform init

      - name: Terraform Apply
        working-directory: ./middleware-service/terraform
        run: terraform apply -auto-approve \
          -var="jwt_secret=${{ secrets.JWT_SECRET }}"

  notify:
    if: always()
    needs: [build, deploy]
    uses: ./.github/workflows/job-notify-build.yaml
    with:
      build_status: ${{ needs.deploy.result }}
    secrets:
      DISCORD_BUILD_WEBHOOK: ${{ secrets.DISCORD_BUILD_WEBHOOK }}
