name: Deploy FastFoodSoatLambdaCredential Auth

on:
  workflow_call:
    inputs:
      environment:
        required: false
        type: string
    secrets:
      AWS_ROLE_TO_ASSUME:
        required: true
      S3_BUCKET:
        required: true
      JWT_SECRET:
        required: true
      DB_USER:
        required: true
      DB_PASSWORD:
        required: true
      DB_HOST:
        required: true
      DB_NAME:
        required: true
      DISCORD_BUILD_WEBHOOK:
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: sa-east-1

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew :auth-service:clean :auth-service:shadowJar

      - name: Package Lambda
        run: zip -j auth-service/terraform/auth-service.zip auth-service/build/libs/*-all.jar

      - name: Upload Lambda Artifact
        uses: actions/upload-artifact@v4
        with:
          name: auth-service-zip
          path: auth-service/terraform/auth-service.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Download Lambda Artifact
        uses: actions/download-artifact@v4
        with:
          name: auth-service-zip
          path: auth-service/terraform/

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: sa-east-1

      - name: Terraform Init
        working-directory: ./auth-service/terraform
        run: terraform init

      - name: Terraform Format Check
        if: github.event_name == 'pull_request'
        working-directory: ./auth-service/terraform
        run: terraform fmt -check -recursive

      - name: Terraform Auto Format
        if: github.ref == 'refs/heads/main'
        working-directory: ./auth-service/terraform
        run: terraform fmt -recursive

      - name: Terraform Plan
        if: github.event_name == 'pull_request'
        working-directory: ./auth-service/terraform
        run: terraform plan -input=false

      - name: Terraform Apply
        working-directory: ./auth-service/terraform
        run: |
          terraform apply -auto-approve \
            -var="jwt_secret=${{ secrets.JWT_SECRET }}" \
            -var="db_user=${{ secrets.DB_USER }}" \
            -var="db_password=${{ secrets.DB_PASSWORD }}" \
            -var="db_host=${{ secrets.DB_HOST }}" \
            -var="db_name=${{ secrets.DB_NAME }}"